// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {gitclient} from '../models';

export function Blame(arg1:string,arg2:string,arg3:string,arg4:gitclient.BlameOptions):Promise<Array<gitclient.BlameLine>>;

export function CancelMergeTool():Promise<void>;

export function Checkout(arg1:string,arg2:string):Promise<string>;

export function ChooseRepository():Promise<string>;

export function Commit(arg1:string,arg2:string,arg3:boolean):Promise<string>;

export function CommitDetails(arg1:string,arg2:string):Promise<gitclient.CommitDetails>;

export function CommitFiles(arg1:string,arg2:string):Promise<Array<string>>;

export function CommitInfo(arg1:string,arg2:string):Promise<gitclient.Commit>;

export function ConfigureMergeTool(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<string>;

export function Conflict(arg1:string,arg2:string):Promise<gitclient.ConflictData>;

export function CopyText(arg1:string):Promise<void>;

export function CreateBranch(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<string>;

export function DeleteBranch(arg1:string,arg2:string,arg3:boolean):Promise<string>;

export function Diff(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function Discard(arg1:string,arg2:Array<string>,arg3:boolean):Promise<string>;

export function FetchAll(arg1:string,arg2:boolean):Promise<string>;

export function FileContent(arg1:string,arg2:string,arg3:string,arg4:string):Promise<gitclient.FileContent>;

export function FileDiff(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<string>;

export function FileHistory(arg1:string,arg2:string,arg3:string):Promise<Array<gitclient.FileRevision>>;

export function HistorySnapshot(arg1:string,arg2:number,arg3:string):Promise<gitclient.Snapshot>;

export function Identity(arg1:string):Promise<gitclient.Identity>;

export function InitialRepository():Promise<string>;

export function MergeTools(arg1:string):Promise<Array<gitclient.MergeTool>>;

export function Pull(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function Push(arg1:string,arg2:gitclient.PushOptions):Promise<string>;

export function RefAction(arg1:string,arg2:gitclient.RefOptions):Promise<string>;

export function Reflog(arg1:string):Promise<Array<gitclient.StashEntry>>;

export function RepositoryExists(arg1:Array<string>):Promise<Record<string, boolean>>;

export function Reset(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ResolveConflict(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function RunDiffTool(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<string>;

export function RunMergeTool(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SetIdentity(arg1:string,arg2:string,arg3:string):Promise<string>;

export function Snapshot(arg1:string,arg2:number):Promise<gitclient.Snapshot>;

export function Stage(arg1:string,arg2:Array<string>):Promise<string>;

export function StartReview(arg1:string,arg2:gitclient.ReviewOptions):Promise<string>;

export function StashAction(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean,arg6:boolean,arg7:boolean):Promise<string>;

export function Stashes(arg1:string):Promise<Array<gitclient.StashEntry>>;

export function Unstage(arg1:string,arg2:Array<string>):Promise<string>;

export function WorkingState(arg1:string):Promise<gitclient.WorkingState>;
