// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Blame(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Blame'](arg1, arg2, arg3, arg4);
}

export function CancelMergeTool() {
  return window['go']['main']['App']['CancelMergeTool']();
}

export function Checkout(arg1, arg2) {
  return window['go']['main']['App']['Checkout'](arg1, arg2);
}

export function ChooseRepository() {
  return window['go']['main']['App']['ChooseRepository']();
}

export function Commit(arg1, arg2, arg3) {
  return window['go']['main']['App']['Commit'](arg1, arg2, arg3);
}

export function CommitDetails(arg1, arg2) {
  return window['go']['main']['App']['CommitDetails'](arg1, arg2);
}

export function CommitFiles(arg1, arg2) {
  return window['go']['main']['App']['CommitFiles'](arg1, arg2);
}

export function CommitInfo(arg1, arg2) {
  return window['go']['main']['App']['CommitInfo'](arg1, arg2);
}

export function ConfigureMergeTool(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ConfigureMergeTool'](arg1, arg2, arg3, arg4);
}

export function Conflict(arg1, arg2) {
  return window['go']['main']['App']['Conflict'](arg1, arg2);
}

export function CopyText(arg1) {
  return window['go']['main']['App']['CopyText'](arg1);
}

export function CreateBranch(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateBranch'](arg1, arg2, arg3, arg4);
}

export function DeleteBranch(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteBranch'](arg1, arg2, arg3);
}

export function Diff(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Diff'](arg1, arg2, arg3, arg4);
}

export function Discard(arg1, arg2, arg3) {
  return window['go']['main']['App']['Discard'](arg1, arg2, arg3);
}

export function FetchAll(arg1, arg2) {
  return window['go']['main']['App']['FetchAll'](arg1, arg2);
}

export function FileContent(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['FileContent'](arg1, arg2, arg3, arg4);
}

export function FileDiff(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['FileDiff'](arg1, arg2, arg3, arg4);
}

export function FileHistory(arg1, arg2, arg3) {
  return window['go']['main']['App']['FileHistory'](arg1, arg2, arg3);
}

export function HistorySnapshot(arg1, arg2, arg3) {
  return window['go']['main']['App']['HistorySnapshot'](arg1, arg2, arg3);
}

export function Identity(arg1) {
  return window['go']['main']['App']['Identity'](arg1);
}

export function InitialRepository() {
  return window['go']['main']['App']['InitialRepository']();
}

export function MergeTools(arg1) {
  return window['go']['main']['App']['MergeTools'](arg1);
}

export function Pull(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Pull'](arg1, arg2, arg3, arg4);
}

export function Push(arg1, arg2) {
  return window['go']['main']['App']['Push'](arg1, arg2);
}

export function RefAction(arg1, arg2) {
  return window['go']['main']['App']['RefAction'](arg1, arg2);
}

export function Reflog(arg1) {
  return window['go']['main']['App']['Reflog'](arg1);
}

export function RepositoryExists(arg1) {
  return window['go']['main']['App']['RepositoryExists'](arg1);
}

export function Reset(arg1, arg2, arg3) {
  return window['go']['main']['App']['Reset'](arg1, arg2, arg3);
}

export function ResolveConflict(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ResolveConflict'](arg1, arg2, arg3, arg4);
}

export function RunDiffTool(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['RunDiffTool'](arg1, arg2, arg3, arg4, arg5);
}

export function RunMergeTool(arg1, arg2, arg3) {
  return window['go']['main']['App']['RunMergeTool'](arg1, arg2, arg3);
}

export function SetIdentity(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetIdentity'](arg1, arg2, arg3);
}

export function Snapshot(arg1, arg2) {
  return window['go']['main']['App']['Snapshot'](arg1, arg2);
}

export function Stage(arg1, arg2) {
  return window['go']['main']['App']['Stage'](arg1, arg2);
}

export function StartReview(arg1, arg2) {
  return window['go']['main']['App']['StartReview'](arg1, arg2);
}

export function StashAction(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['StashAction'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function Stashes(arg1) {
  return window['go']['main']['App']['Stashes'](arg1);
}

export function Unstage(arg1, arg2) {
  return window['go']['main']['App']['Unstage'](arg1, arg2);
}

export function WorkingState(arg1) {
  return window['go']['main']['App']['WorkingState'](arg1);
}
